---
apiVersion: v1
kind: Secret
metadata:
  name: awx-demo-admin-password
  namespace: awx
stringData:
  password: admin
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  service_type: ClusterIP
  ingress_type: ingress
  hostname: awx-demo.localhost
  ingress_annotations: |
    kubernetes.io/ingress.class: traefik