apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    # kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
  valuesContent: |-
    image:
      name: traefik
      tag: 2.7.0
    dashboard:
      enabled: true
      domain: "traefik.localhost"
    ports:
      traefik:
        expose: true
      websecure:
        tls:
          enabled: true
    logs:
      access:
        enabled: false
---
